### ISSUE TITLE
Refresh on variable change

### ISSUE THREAD

**Issue by CourchesneA** [innius/grafana-video-panel#13]
Great plugin, I was able to quickly get my setup working with variables. When I change one of my variables (i.e. from stage="staging" to stage="production"), all my panels refresh and show updated values, except for this video panel. If I reload the window, it shows the updated video. Would it be possible to add a hook for variable changes ?

**Comment by rvdwijngaard** [comment]
Thanks for your feedback. I understand the issue but I am not sure if the standard API supports this. Is there a hook for variable changes ?

**Comment by rvdwijngaard** [comment]
If I read [this thread](https://community.grafana.com/t/how-to-listen-for-when-a-variable-changes/55665/21) I suspect your problem is caused by a bug in grafana.

**Comment by CourchesneA** [comment]
I was actually just looking into this today. Thanks for the demo, I can verify that it does work as expected. I was using the `file` option (sorry, I forgot to mention it in the original post), but when I switch to `iframe` it gets refreshed as expected. Thanks !
