### ISSUE TITLE
ASP .NET authorize issue

### ISSUE THREAD

**Issue by micuentadecasa** [innius/grafana-video-panel#14]
Hi, I'm loading an ASP .NET page with the iframe option, it works ok except for the pages that I mark with the authorize directive, in that case, your panel appears in blank, if I see the frame source, I can see that it has redirected to the login page, the html is ok but still it only shows a blank page, any clue?

regards.

**Comment by rvdwijngaard** [comment]
Hi, to be honest I don't have a clue. Do you see any error messages in the Developer Console of your browser?

**Comment by micuentadecasa** [comment]
Hi @rvdwijngaard , I have been checking it and it seems the issue is related to Grafana behaviour, not your plugin. I'm receiving in some cases a 405, as said, it seems that Grafana is not able to send headers and then the server rejects the connection, and the solution seems to be to install Grafana with a reverse proxy like NGINX. I will try and revert to you.

thanks again.
Regards.

**Comment by rvdwijngaard** [comment]
@micuentadecasa that sounds reasonable. Were you able to verify this?

**Comment by micuentadecasa** [comment]
we solved it, now it is easier even, we put the NGINX reverse proxy before all the services, and we can use relative URLs and not expose the real URLs.

Please close this Issue. Thanks @rvdwijngaard .
