### ISSUE TITLE
Issues with Grafana 9

### ISSUE THREAD

**Issue by AbsolutOD** [innius/grafana-video-panel#15]
I am building a new grafana server and installed version 9.  I installed your plugin.  It shows that it is installed and I see it in the plugin directory on the file system.  However, I can't see it in the library panel.

I noticed that the last commit was that some libs were updated for grafana version 8.0.2.  Might that conflict with version 9 or am I missing something completely obvious?

**Comment by rvdwijngaard** [comment]
As far as I can see this plugin works fine with v9.0; I have tested this: 
```
docker run -it -p 3000:3000 --e GF_INSTALL_PLUGINS="innius-video-panel" grafana/grafana:9.0.0
```
and the panel can be used within grafana without any trouble.

**Comment by AbsolutOD** [comment]
I see it now.  I was looking in the panel library.  I see now that it is under the visualizations when I create a new panel.  Sorry to miss that.
