### ISSUE TITLE
Resize the iframe

### ISSUE THREAD

**Issue by RomeroGaliza** [innius/grafana-video-panel#18]
Is it possible to resize the iframe?

**Comment by rvdwijngaard** [comment]
why would you want to resize the iframe?

**Comment by LyudmilaSK** [comment]
# [rvdwijngaard](https://github.com/rvdwijngaard), I want to crop the frame of the video stream as there is unnecessary information on the edges of the image. Is it possible?

**Comment by rvdwijngaard** [comment]
@LyudmilaSK this is currently not supported. Feel free to make a pull request :-)
