### ISSUE TITLE
Support m3u8 live video url

### ISSUE THREAD

**Issue by jinleileiking** [innius/grafana-video-panel#19]

**Comment by rvdwijngaard** [comment]
hi @jinleileiking thanks for creating this issue. I am not familiar with `m3u8`. Do you have some more information about this and, more importantly, is this supported by standard browsers? This plugin can only use standard browser capabilities. I don't want to pull in third party libraries.

**Comment by jinleileiking** [comment]
chrome needs js to play m3u8. 
See https://github.com/video-dev/hls.js/  https://github.com/videojs/video.js

**Comment by jinleileiking** [comment]
safari can play with no js.

**Comment by rvdwijngaard** [comment]
I don't see a way to support this without pulling in third party libraries.
