### ISSUE TITLE
Can we pass variable parameters from grafana to iframe url?

### ISSUE THREAD

**Issue by satyamtpatel** [innius/grafana-video-panel#2]

**Comment by satyamtpatel** [comment]
How we can add variable parameters from grafana to iframe url? We have requirement to add parameter that represent dynamic values that we need to pass to iframe url.

**Comment by grosseruser** [comment]
I have a dynamically generated weather video. But since it always has the same name, the browser takes it from the cache. Can I somehow append a randomly generated parameter to the url or a timestamp?

**Comment by rvdwijngaard** [comment]
@satyamtpatel I am not completely sure about your requirement. Do you mean you want to define dashboard variables and use them in the url of the panel? so for example, you define variable foo. In the plugin you define something like 
```
https://example.com?foo=${foo}
```

**Comment by rvdwijngaard** [comment]
fixed with https://github.com/innius/grafana-video-panel/commit/8480ad2c613f8d9988b903c7695bb4fc131d736d
