### ISSUE TITLE
Can't display video stream from django backend using iframe

### ISSUE THREAD

**Issue by Chewgithub** [innius/grafana-video-panel#20]
Thank you so much for creating this plugin. 

Have anyone tried using camera stream from localhost, which streaming from django local app, using OpenCV? 
I have tried flask with no issue, however django app just refuse to connect. 

![image](https://github.com/innius/grafana-video-panel/assets/97344204/039a703e-9d81-461f-b4b3-eb6f1a1c9a40)

**Comment by rvdwijngaard** [comment]
I am sorry but I don't think this is related to this plugin since it only uses plain javascript without any third party libraries. I am not familiar with django. Do you see any error messages in the Developer Console of your browser?
