### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by Arjak11** [innius/grafana-video-panel#22]
Hi there, 

I'm new to this panel and I'm running Grafana v.9.4.7.  I'm trying to run the innius-video-panel-1.0.7, but it says it is unsigned on the plugin page.

Found this closed thread from ~2 years ago saying that it was signed.  https://github.com/innius/grafana-video-panel/issues/9

I tried to uninstall the plugin but unsuccessfully with a prompt stating can not uninstall a core plugin; also tried to allow the loading of unsigned plugins in the config file but still won't load it properly upon restarting the grafana.

I also tried to manually install the 1.0.7 panel in the grafana/plugins folder yet still no luck... 

Could you please advise what else I can or I should do to use this video panel?  

Much appreciated!

**Comment by rvdwijngaard** [comment]
Hello @Arjak11 

Thanks for your issue. As far as I know there is nothing wrong with the signature of the plugin. I have it running in many different instances (both on premise and grafana cloud instances). I have never seen this error. This plugin is certainly not a core plugin so I suspect you are not managing the plugins correctly. Please checkout the grafana docs once more for more details about how to install plugins. 

Kind Regards,
Ron
