### ISSUE TITLE
Great plugin !

### ISSUE THREAD

**Issue by HB9VQQ** [innius/grafana-video-panel#4]
Very nice work thank you. Big deal to make the plugin work with this http://muf.hb9vqq.ch/ ?

Thank you
Roland

**Comment by rvdwijngaard** [comment]
Hi, 

That is possible by adding using the `iframe` option. This option allows you to select an URL.

**Comment by HB9VQQ** [comment]
Unfortunately, it is not working with the URL given above

**Comment by rvdwijngaard** [comment]
What exactly is the issue you are facing? I tried to use this url and it works fine. Am I missing something?

**Comment by HB9VQQ** [comment]
Okay, thanks for testing then it must be some problem on my side. I just get a black Panel 
![image](https://user-images.githubusercontent.com/75934980/125139497-ec975880-e110-11eb-862d-a6dc55b967b5.png)

**Comment by rvdwijngaard** [comment]
I have tried it again and I think I know why this video is not displayed. My grafana instance uses `https` while this link does not `http`. Mixing https with http is blocked by most browsers by default. 
![Screenshot from 2021-07-12 08-52-59](https://user-images.githubusercontent.com/7237796/125243648-a5ff5500-e2ee-11eb-9f4e-42a6b8b612fe.png)

**Comment by HB9VQQ** [comment]
Thanks for the investigation, much appreciated. After switching to HTTPS it is working now.
