### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by ThoWoKi** [innius/grafana-video-panel#9]
Plugin can not be loaded due to "missing Signature" in Grafana 8.0.0

https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/

![2021-06-11 13_55_29-Window1](https://user-images.githubusercontent.com/3208396/121682854-e3d54780-cabc-11eb-87f9-467d43c807ff.png)

**Comment by u31s** [comment]
me too
I modified default.ini to add "allow_loading_unsigned_plugins = innius-video-panel"
It doesn't work
Very useful panel, pls fix it,tks

**Comment by u31s** [comment]
work well on 7.5.1
can not be loaded due to "missing Signature" in Grafana 8.0.2

**Comment by H3ndrik-Jan** [comment]
I get the same error (missing signature) in Grafana 8.0.3

**Comment by brettawaytoday** [comment]
Is there any way that we can help with this? It's a great plugin!!

**Comment by rvdwijngaard** [comment]
I've signed the plugin; A new version will be available soon.
